In [1]:
import time

In [2]:
time.time()

1528275865.6778688

In [3]:
type(time.time())

float

In [4]:
localtime = time.localtime(time.time())

In [5]:
localtime

time.struct_time(tm_year=2018, tm_mon=6, tm_mday=6, tm_hour=12, tm_min=6, tm_sec=4, tm_wday=2, tm_yday=157, tm_isdst=0)

In [6]:
localtime = time.asctime( time.localtime(time.time()) )

In [7]:
localtime

'Wed Jun  6 12:06:43 2018'

In [8]:
import calendar

In [9]:
cal = calendar.month(2008, 1)

In [10]:
cal

'    January 2008\nMo Tu We Th Fr Sa Su\n    1  2  3  4  5  6\n 7  8  9 10 11 12 13\n14 15 16 17 18 19 20\n21 22 23 24 25 26 27\n28 29 30 31\n'

In [11]:
print(cal)

    January 2008
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31



In [12]:
lst = [1, 2, 3]

In [13]:
if lst:
    for item in lst:
        print(item)

1
2
3


In [14]:
lst = []

In [15]:
if lst:
    for item in lst:
        print(item)

In [16]:
import request

In [17]:
r = requests.get('https://api.github.com/user', auth=('user', 'pass'))

NameError: name 'requests' is not defined

In [19]:
import requests

In [20]:
r = requests.get('https://api.github.com/user', auth=('user', 'pass'))

In [21]:
r.status_code

403

In [24]:
r = requests.get('https://api.github.com/user', auth=('KirillVladimirov', '1598642q'))

In [25]:
r.status_code

200

In [26]:
r.headers

{'Server': 'GitHub.com', 'Date': 'Wed, 06 Jun 2018 13:38:23 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Status': '200 OK', 'X-RateLimit-Limit': '5000', 'X-RateLimit-Remaining': '4998', 'X-RateLimit-Reset': '1528293480', 'Cache-Control': 'private, max-age=60, s-maxage=60', 'Vary': 'Accept, Authorization, Cookie, X-GitHub-OTP', 'ETag': 'W/"29efb0f18c8b983136bd20cd16f45709"', 'Last-Modified': 'Tue, 05 Jun 2018 08:51:54 GMT', 'X-GitHub-Media-Type': 'github.v3; format=json', 'Access-Control-Expose-Headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-o

In [27]:
r.headers['content-type']

'application/json; charset=utf-8'

In [28]:
r.encoding

'utf-8'

In [29]:
r.text

'{"login":"KirillVladimirov","id":2954405,"node_id":"MDQ6VXNlcjI5NTQ0MDU=","avatar_url":"https://avatars2.githubusercontent.com/u/2954405?v=4","gravatar_id":"","url":"https://api.github.com/users/KirillVladimirov","html_url":"https://github.com/KirillVladimirov","followers_url":"https://api.github.com/users/KirillVladimirov/followers","following_url":"https://api.github.com/users/KirillVladimirov/following{/other_user}","gists_url":"https://api.github.com/users/KirillVladimirov/gists{/gist_id}","starred_url":"https://api.github.com/users/KirillVladimirov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/KirillVladimirov/subscriptions","organizations_url":"https://api.github.com/users/KirillVladimirov/orgs","repos_url":"https://api.github.com/users/KirillVladimirov/repos","events_url":"https://api.github.com/users/KirillVladimirov/events{/privacy}","received_events_url":"https://api.github.com/users/KirillVladimirov/received_events","type":"User","site_admin":fal

In [30]:
r.json()

{'login': 'KirillVladimirov',
 'id': 2954405,
 'node_id': 'MDQ6VXNlcjI5NTQ0MDU=',
 'avatar_url': 'https://avatars2.githubusercontent.com/u/2954405?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/KirillVladimirov',
 'html_url': 'https://github.com/KirillVladimirov',
 'followers_url': 'https://api.github.com/users/KirillVladimirov/followers',
 'following_url': 'https://api.github.com/users/KirillVladimirov/following{/other_user}',
 'gists_url': 'https://api.github.com/users/KirillVladimirov/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/KirillVladimirov/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/KirillVladimirov/subscriptions',
 'organizations_url': 'https://api.github.com/users/KirillVladimirov/orgs',
 'repos_url': 'https://api.github.com/users/KirillVladimirov/repos',
 'events_url': 'https://api.github.com/users/KirillVladimirov/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/KirillVladimirov/re

In [31]:
l = [[1,2,3], [4,5,6]]

In [32]:
[lll * 2 for ll in l for lll in ll]

[2, 4, 6, 8, 10, 12]

In [33]:
l = [[] for _ in range(5)]

In [34]:
l

[[], [], [], [], []]

In [35]:
'Hello world!'.encode('rot13')

LookupError: 'rot13' is not a text encoding; use codecs.encode() to handle arbitrary codecs

In [36]:
r = requests.get('https://api.github.com/events')

In [37]:
import time

In [38]:
time.time()

1528378636.9961398

In [39]:
time.time()

1528379152.0565622

In [40]:
import datetime

In [41]:
datetime.datetime.now()

datetime.datetime(2018, 6, 7, 16, 47, 51, 198822)

In [42]:
datetime.timedelta(days=1, hours=3)

datetime.timedelta(1, 10800)

In [46]:
from tzlocal import get_localzone

ModuleNotFoundError: No module named 'tzlocal'

In [45]:
SERVER_TZ = get_localzone()

NameError: name 'get_localzone' is not defined

In [44]:
datetime.datetime.now(tz=SERVER_TZ) + datetime.timedelta(days=1, hours=3)

NameError: name 'SERVER_TZ' is not defined

In [47]:
lst = []

In [48]:
lst is False

False

In [49]:
bool(lst) is False

True

In [53]:
if not lst:
    print(1)

1


In [52]:
len(lst)

0

In [54]:
def myfunc(x, y, z):
    print(x, y, z)

In [55]:
tuple_vec = (1, 0, 1)
dict_vec = {'x': 1, 'y': 0, 'z': 1}

In [56]:
myfunc(*tuple_vec)

1 0 1


In [57]:
myfunc(**dict_vec)

1 0 1


In [58]:
import numpy as np
lst = [5, 10, 15, 20]
vector = np.array(lst)
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [59]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
type(matrix)

numpy.ndarray

In [61]:
vector = np.array([10, 20, 30])
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [62]:
vector

array([10, 20, 30])

In [63]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [1]:
lst = []

In [2]:
i = lst[0]

IndexError: list index out of range

In [3]:
i = lst[:1]

In [4]:
i

[]